[build-system]
requires = [
  "meson-python",
  "meson>=1.0.0",
  "ninja",
  "numpy>=2.0"
]
build-backend = "mesonpy"

[project]
name = "outflowpy"
version = "0.0.2"
description = "Outflow field modelling"
requires-python = ">=3.9"
dependencies = ["numpy",  "astropy", "matplotlib","sunpy","reproject","mpl_animators","bs4","lxml","zeep","drms","scikit-image", "pyvista", "streamtracer"]

[tool.meson-python]
limited-api = false
