name: Test Outflowpy build

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (host, not build env)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 'latest'
        
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build single wheel for testing
        env:
          CIBW_BUILD: "cp313-manylinux_x86_64"
          
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Create test venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install wheel for testing
        run: |
          source .venv/bin/activate
          pip install wheelhouse/*.whl
          pip install pytest 

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -v -s --tb=long outflowpy/tests
