name: Build Linux wheels for Python >=3.9

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (host, not build env)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 'latest'

      # - name: Install gfortran (macOS)
      #   if: runner.os == 'macOS'
      #   run: |
      #     ln -s /opt/homebrew/bin/gfortran-15 /opt/homebrew/bin/gfortran || true
      #     echo "/opt/homebrew/bin" >> $GITHUB_PATH

      # - name: Install gfortran (Windows)
      #   if: runner.os == 'Windows'
      #   run: |
      #     choco install mingw -y
      #     echo "C:\ProgramData\mingw64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # - name: Setup Fortran (Windows)
      #   if: runner.os == 'Windows'
      #   uses: fortran-lang/setup-fortran@v1
        
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD: "cp313-*"
          CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=15.0"
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name:  wheels-${{ runner.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl
